name: Build and User Approval Workflow
on:
  push:
    branches:
      - master

jobs:
  Approval-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Request approval'
        id: approval
        env:
          ashoklogicfocus: ${{ secrets.PAT }}
        run: |
          const github = require('ashoklogicfocus');
          const octokit = new github.GitHub(process.env.PAT);
          const result = await octokit.pulls.requestReviewers({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            pull_number: github.context.payload.pull_request.number,
            reviewers: ['ashoklogicfocus']
          });
          console.log(result);

  Rejection-Stage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Reject pull request'
        run: |
          Write-Host 'Rejecting pull request'
          # Add any rejection steps you need here
