name: Build and User Approval Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Approval-Stage:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: 'Request approval'
        id: approval
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          const github = require('ashoklogicfocus@actions/github');
          const octokit = new github.GitHub(process.env.PAT);
          const result = await octokit.pulls.requestReviewers({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            pull_number: github.context.payload.pull_request.number,
            reviewers: ['ashoklogicfocus']
          });
          console.log(result);

  Rejection-Stage:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'changes_requested'
    steps:
      - name: 'Reject pull request'
        run: |
          Write-Host 'Rejecting pull request'
          # Add any rejection steps you need here
