name: Java Gradle Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'# Replace with the desired Java version
          distribution: 'adopt'
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
  
        run: ./gradlew build
        
      - name: Package
        run: ./gradlew assemble
